In [1]:
import numpy as np

In [2]:

arr=np.array([10,20,30,40,50])
print(arr+2)
print(arr*3)
print(arr/2)

[12 22 32 42 52]
[ 30  60  90 120 150]
[ 5. 10. 15. 20. 25.]


In [3]:
arr=np.array([1, 2, 3, 6, 4, 5])
print(arr[::-1])

[5 4 6 3 2 1]


In [4]:
x=np.array([1,2,3,4,5,1,2,1,1,1])
values, counts=np.unique(x, return_counts=True)
freq=values[np.argmax(counts)]
print("Most frequent value ", freq)
print("Indices ",np.where(x == freq)[0])

Most frequent value  1
Indices  [0 5 7 8 9]


In [5]:
y=np.array([1,1,1,2,3,4,2,4,3,3])
values, counts=np.unique(y, return_counts=True)
freq=values[np.argmax(counts)]
print("Most frequent value:", freq)
print("Indices:", np.where(y == freq)[0])

Most frequent value: 1
Indices: [0 1 2]


In [6]:
arr=np.array([[10,20,30],
                [40,50,60],
                [70,80,90]])

print(arr[0,1])
print(arr[2,0])

20
70


In [7]:
Harsimrat_Singh=np.linspace(10, 100, 25)
print(Harsimrat_Singh)
print("Dimensions:", Harsimrat_Singh.ndim)
print("Shape:", Harsimrat_Singh.shape)
print("Total elements:", Harsimrat_Singh.size)
print("Data type:", Harsimrat_Singh.dtype)
print("Total bytes:", Harsimrat_Singh.nbytes)
transpose = Harsimrat_Singh.reshape(25,1)
print(transpose)
print(Harsimrat_Singh.T)
print("For a 1-D array, T does not change its shape.")

[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimensions: 1
Shape: (25,)
Total elements: 25
Data type: float64
Total bytes: 200
[[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
For a 1-D array, T does not change its shape.


In [8]:
ucs420_Harsimrat_Singh = np.array([[10,20,30,40],
                         [50,60,70,80],
                         [90,15,20,35]])

print("Mean:", np.mean(ucs420_Harsimrat_Singh))
print("Median:", np.median(ucs420_Harsimrat_Singh))
print("Maximum:", np.max(ucs420_Harsimrat_Singh))
print("Minimum:", np.min(ucs420_Harsimrat_Singh))
print("Unique elements:", np.unique(ucs420_Harsimrat_Singh))
reshaped_ucs420_Harsimrat_Singh = ucs420_Harsimrat_Singh.reshape(4,3)
print(reshaped_ucs420_Harsimrat_Singh)
resized_ucs420_vansh = np.resize(ucs420_Harsimrat_Singh, (2,3))
print(resized_ucs420_vansh)

Mean: 43.333333333333336
Median: 37.5
Maximum: 90
Minimum: 10
Unique elements: [10 15 20 30 35 40 50 60 70 80 90]
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
[[10 20 30]
 [40 50 60]]
